<?php
/** @var \Ryvon\EventLog\Block\Adminhtml\Digest\EntryBlock $block */
$entry = $block->getEntry();
if (!$entry) {
    return;
}

$duplicates = $block->getData('duplicates');
$storeView = null;
$colspan = 1;
if (!$block->getData('single-store-mode')) {
    $storeView = $entry->getEntryContext()->getData('store-view');
    if (!$storeView) {
        $colspan = 2;
    }
}
?>
<tr class="data-row <?php echo $block->escapeHtmlAttr($block->getRowClass($entry)); ?>">
    <td class="log-time">
        <div class="data-grid-cell-content"
             title="<?php echo $block->escapeHtmlAttr($block->formatTitleTime($entry->getCreatedAtDateTime())); ?>">
            <?php echo $block->escapeHtml($block->formatLogTime($entry->getCreatedAtDateTime())); ?>
        </div>
    </td>
    <td class="log-message" colspan="<?php echo $colspan; ?>">
        <div class="data-grid-cell-content">
            <?php echo $block->replacePlaceholders($entry->getEntryMessage(), $entry->getEntryContext()); ?>
            <?php if ($duplicates > 1) {
                $displayCount = number_format($duplicates - 1);
                ?>
                <span class="duplicate-count" title="<?php echo str_replace(
                    ['{count}'],
                    [$displayCount],
                    $displayCount === '1'
                        ? '{count} duplicate of this message was hidden, this is the most recent.'
                        : '{count} duplicates of this message were hidden, this is the most recent.'
                ); ?>">
                    +<?php echo $displayCount; ?>
                </span>
                <?php
            } ?>
        </div>
    </td>
    <?php
    if ($storeView) {
        ?>
        <td class="log-store-view">
            <div class="data-grid-cell-content"><?php echo $block->escapeHtml($storeView); ?></div>
        </td>
        <?php
    }

    if ($block->getData('user-column')) {
        $userContext = $entry->getEntryContext()->getData('.user');
        ?>
        <td class="log-user-name">
            <div class="data-grid-cell-content"><?php
                if ($userContext) {
                    echo $block->replacePlaceholders('{user}', ['user' => $userContext]);
                }
                ?></div>
        </td>
        <td class="log-user-ip">
            <div class="data-grid-cell-content"><?php
                if ($userContext) {
                    echo $block->replacePlaceholders('{ip-address}', ['ip-address' => $userContext['ip-address'] ?? '']);
                }
                ?></div>
        </td>
        <?php
    }
    ?>
</tr>
