<?php
/** @var \Ryvon\EventLog\Block\Adminhtml\Digest\OrderBlock $block */
$entry = $block->getEntry();
if (!$entry) {
    return;
}

$context = $entry->getEntryContext();
$incrementId = $context->getData('order');
$orderId = $context->getData('order-id');

if (!$incrementId) {
    return;
}
?>
<tr class="data-row <?php echo $block->escapeHtmlAttr($block->getRowClass($entry)); ?>">
    <td>
        <div class="data-grid-cell-content">
            <?php if ($orderId) { ?>
                <a target="_blank" href="<?php echo $block->escapeUrl($block->getOrderUrl($orderId)); ?>">
                    <?php echo $block->escapeHtml($incrementId); ?>
                </a>
            <?php } else { ?>
                <?php echo $block->escapeHtml($incrementId); ?>
            <?php } ?>
        </div>
    </td>
    <td>
        <div class="data-grid-cell-content" title="<?php echo $block->escapeHtmlAttr($block->formatTitleTime($entry->getCreatedAtDateTime())); ?>">
            <?php echo $block->escapeHtml($block->formatOrderTime($context->getData('created-at'))); ?>
        </div>
    </td>
    <td>
        <div class="data-grid-cell-content"><?php echo $block->escapeHtml($context->getData('bill-to-name')); ?></div>
    </td>
    <td>
        <div class="data-grid-cell-content"><?php echo $block->escapeHtml($block->formatPrice($context->getData('price'))); ?></div>
    </td>
    <td>
        <div class="data-grid-cell-content"><?php echo $block->escapeHtml($context->getData('status')); ?></div>
    </td>
    <td>
        <div class="data-grid-cell-content"><?php echo $block->escapeHtml($context->getData('payment-method')); ?></div>
    </td>
    <?php if (!$block->getData('single-store-mode')) { ?>
        <td>
            <div class="data-grid-cell-content"><?php echo $block->escapeHtml($context->getData('store-view')); ?></div>
        </td>
    <?php } ?>
    <td class="ip">
        <div class="data-grid-cell-content">
            <?php
            $ips = $context->getData('ips') ?: [];
            if ($ips && is_array($ips)) {
                $ips = array_unique($ips);
                foreach ($ips as $ip) {
                    echo $block->formatIpAddress($ip) . '<br/>';
                }
            }
            ?>
        </div>
    </td>
</tr>
