<?php
/** @var \Ryvon\EventLog\Block\Adminhtml\TemplateBlock $block */

$colspan = 2;
if ($block->getData('user-column')) {
    $colspan += 2;
}

// If we are not in single store mode we may have a store view column visible
if (!$block->getData('single-store-mode')) {
    $colspan++;
}
?>
<tr>
    <th class="data-grid-th" colspan="<?php echo $colspan; ?>">
        <span class="data-grid-cell-content">
            <span class="group-title"><?php echo $block->escapeHtml($block->getData('title')); ?></span>
            <?php
            $links = $block->getData('links');
            if ($links) {
                echo $block->renderBlock('Ryvon_EventLog::heading/links.phtml', \Magento\Backend\Block\Template::class, [
                    'links' => $links,
                ]);
            }
            ?>
            <small class="group-message"><?php echo $block->escapeHtml($block->getData('summary')); ?></small>
        </span>
    </th>
</tr>
