<?php
/** @var \Magento\Backend\Block\Template $block */

$colspan = 2;
if ($block->getData('user-column')) {
    $colspan += 2;
}

// If we are not in single store mode we may have a store view column visible
if (!$block->getData('single-store-mode')) {
    $colspan++;
}
?>
<tr>
    <th class="data-grid-th" colspan="<?php echo $colspan; ?>">
        <span class="data-grid-cell-content">
            <span class="group-title"><?php echo $block->getData('title'); ?></span>
            <?php echo $block->getData('links') ?: ''; ?>
            <small class="group-message"><?php echo $block->getData('summary'); ?></small>
        </span>
    </th>
</tr>
