<?php
/** @var \Ryvon\EventLog\Block\Adminhtml\TemplateBlock $block */

?>
<tr>
    <th class="data-grid-th" colspan="10">
        <span class="data-grid-cell-content">
            <span class="group-title"><?php echo $block->escapeHtml($block->getData('title')); ?></span>
            <?php
            $links = $block->getData('links');
            if ($links) {
                echo $block->renderBlock('Ryvon_EventLog::heading/links.phtml', \Magento\Backend\Block\Template::class, [
                    'links' => $links,
                ]);
            }
            ?>
            <small class="group-message"><?php echo $block->escapeHtml($block->getData('summary')); ?></small>
        </span>
    </th>
</tr>
<tr>
    <th class="data-grid-th">
        <div class="data-grid-cell-content"><?php echo __('ID'); ?></div>
    </th>
    <th class="data-grid-th">
        <div class="data-grid-cell-content"><?php echo __('Purchase Date'); ?></div>
    </th>
    <th class="data-grid-th">
        <div class="data-grid-cell-content"><?php echo __('Bill-to Name'); ?></div>
    </th>
    <th class="data-grid-th">
        <div class="data-grid-cell-content"><?php echo __('Grand Total'); ?></div>
    </th>
    <th class="data-grid-th">
        <div class="data-grid-cell-content"><?php echo __('Status'); ?></div>
    </th>
    <th class="data-grid-th">
        <div class="data-grid-cell-content"><?php echo __('Payment Method'); ?></div>
    </th>
    <?php if (!$block->getData('single-store-mode')) { ?>
        <th class="data-grid-th">
            <div class="data-grid-cell-content"><?php echo __('Store'); ?></div>
        </th>
    <?php } ?>
    <th class="data-grid-th">
        <div class="data-grid-cell-content"><?php echo __('IP'); ?></div>
    </th>
</tr>
