<?php
/** @var \Ryvon\EventLog\Block\Adminhtml\TemplateBlock $block */

?>
<tr>
    <th class="data-grid-th" colspan="10">
        <span class="data-grid-cell-content">
            <span class="group-title"><?php echo $block->getData('title'); ?></span>
            <?php
            $links = $block->getData('links');
            if ($links) {
                echo $block->renderBlock('Ryvon_EventLog::heading/links.phtml', \Magento\Backend\Block\Template::class, [
                    'links' => $block->getData('links'),
                ]);
            }
            ?>
            <small class="group-message"><?php echo $block->getData('summary'); ?></small>
        </span>
    </th>
</tr>
<tr>
    <th class="data-grid-th"><div class="data-grid-cell-content">ID</div></th>
    <th class="data-grid-th"><div class="data-grid-cell-content">Purchase Date</div></th>
    <th class="data-grid-th"><div class="data-grid-cell-content">Bill-to Name</div></th>
    <th class="data-grid-th"><div class="data-grid-cell-content">Grand Total</div></th>
    <th class="data-grid-th"><div class="data-grid-cell-content">Status</div></th>
    <th class="data-grid-th"><div class="data-grid-cell-content">Payment Method</div></th>
    <?php if (!$block->getData('single-store-mode')) { ?>
        <th class="data-grid-th">
            <div class="data-grid-cell-content">Store</div>
        </th>
    <?php } ?>
    <th class="data-grid-th"><div class="data-grid-cell-content">IP</div></th>
</tr>
