<?php
/** @var \Ryvon\EventLog\Block\Adminhtml\Digest\DateBlock $this */

$current = $this->getCurrentDigest();
if (!$current) {
    return;
}

$previous = $this->getPreviousDigest($current);
$next = $this->getNextDigest($current);
?>
<div class="admin__data-grid-header-row">
    <div style="padding: 0 0 15px 0; text-align: center">
        <?php if ($previous) { ?>
            <button type="button"
                    class="action-previous"
                    title="<?php echo $this->escapeHtmlAttr(__('Previous page')); ?>"
                    onclick="window.location.href = '<?php echo $this->escapeJs($this->getDigestUrl($previous)); ?>';return false;">
                <span><?php echo __('Previous page'); ?></span>
            </button>
        <?php } else { ?>
            <button type="button" class="action-previous disabled">
                <span><?php echo __('Previous page'); ?></span>
            </button>
        <?php } ?>
        <span class="admin__control-support-text" style="margin-right: 10px;">
            <?php if ($current) {
                echo str_replace(
                    [
                        '{date-range}',
                        '{time-range}'
                    ],
                    [
                        $this->getDateRangeBuilder()->buildDateRange($current->getStartedAtDateTime(), $current->getFinishedAtDateTime()),
                        $this->getDateRangeBuilder()->buildTimeRange($current->getStartedAtDateTime(), $current->getFinishedAtDateTime())
                    ],
                    __('Showing {date-range}, {time-range}')
                );
            } else {
                echo __('Unknown date specified');
            } ?>
        </span>
        <?php if ($next) { ?>
            <button type="button"
                    class="action-next"
                    title="<?php echo $this->escapeHtmlAttr(__('Next page')); ?>"
                    onclick="window.location.href = '<?php echo $this->escapeJs($this->getDigestUrl($next)); ?>';return false;">
                <span><?php echo __('Next page'); ?></span>
            </button>
        <?php } else { ?>
            <button type="button" class="action-next disabled">
                <span><?php echo __('Next page'); ?></span>
            </button>
        <?php } ?>
    </div>
</div>
