<?php
/** @var \Ryvon\EventLog\Block\Adminhtml\TemplateBlock $block */
/** @var \Ryvon\EventLog\Helper\Group\GroupInterface $group */

$group = isset($block) ? $block->getData('group') : null;
if (!$group) {
    return;
}

$template = $group->getTemplate();
$collection = $group->getEntryCollection();
$hasUserContext = $collection->hasUserContext();

$odd = false;

?>

<table class="data-grid" style="margin-bottom: 2rem;">
    <thead>
    <?php
    echo $block->renderBlock($template->getHeaderTemplateFile(), $template->getHeaderBlockClass(), [
        'title' => $group->getTitle(),
        'summary' => $collection->buildSummaryMessage(),
        'links' => $group->getHeadingLinks(),
        'user-column' => $hasUserContext,
        'single-store-mode' => $this->getData('single-store-mode'),
    ]);
    ?>
    </thead>
    <?php
    foreach ($collection->getItems() as $entry) {
        echo $block->renderBlock($template->getEntryTemplateFile(), $template->getEntryBlockClass(), [
            'entry' => $entry,
            'odd' => $odd = !$odd,
            'user-column' => $hasUserContext,
            'single-store-mode' => $this->getData('single-store-mode'),
            'duplicates' => $collection->getDuplicateCount($entry),
        ]);
    }
    ?>
</table>
